reg_homepage:
    path:     /register
    defaults: { _controller: RegBundle:Default:index }
regist:
    path:     register/reg
    defaults: { _controller: RegBundle:Default:reg }
  
login:
    path:     /logare
    defaults: { _controller: RegBundle:Default:log}
    
exit:
    path:     /exit
    defaults: { _controller: RegBundle:Default:exit}



add_photo:
    path:     myprofile/photo/add
    defaults: { _controller: RegBundle:Default:AddPhoto}
    
profile:
    path: /profile/{id}
    defaults: { _controller: RegBundle:Default:MyProfile}

Group:
    path: /group/{id}
    defaults: { _controller: RegBundle:Group:group}
    
photo:
    path: profile/{id}/photo
    defaults: { _controller: RegBundle:Default:Photo}
