<?php

namespace RegBundle\Repository;

/**
 * NickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NickRepository extends \Doctrine\ORM\EntityRepository
{
}
