<?php

namespace RegBundle\Repository;

/**
 * UsernameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsernameRepository extends \Doctrine\ORM\EntityRepository
{
}
