chat:
    resource: "@ChatBundle/Resources/config/routing.yml"
    prefix:   /


index:
    resource: "@IndexBundle/Resources/config/routing.yml"
    prefix:   /

reg:
    resource: "@RegBundle/Resources/config/routing.yml"
    prefix:   /

hello:
    resource: "@helloBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"