reg:
    resource: "@RegBundle/Resources/config/routing.yml"
    prefix:   /

hello:
    resource: "@helloBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
